name: Build and Publish Docker
on: 
  workflow_dispatch:
    inputs:
      java_type:
        description: 'Build Openjdk Image Type'
        required: false
        default: 'jdk'
        type: string
      java_version: 
        description: 'Build Openjdk Image Version'
        required: false
        default: '8u412'
        type: string
      java_version_suffix:
        description: 'Build Openjdk Image Version Suffix'
        required: false
        default: 'b08'
        type: string
      java_download_url:
        description: 'Build Openjdk Image Download URL'
        required: false
        default: 'https://github.com/adoptium/temurin8-binaries/releases/download'
        type: string
      java_installed:
        description: 'Build Openjdk Image Installed'
        required: false
        default: 1
        type: number
      os_type: 
        description: 'Build Openjdk Image OS Type'
        required: false
        default: 'debian'
        type: string
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and private service warehouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v3
      - name: Set Docker Tag
        id: set_tag
        run: |
          TAG=${{ github.event.inputs.java_type }}-${{ github.event.inputs.os_type }}
          VERSION_TAG=${{ github.event.inputs.java_version }}-$TAG
          echo "::set-output name=latest::$TAG"
          echo "::set-output name=tag::$VERSION_TAG"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Private service warehouse
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY }}
          username: ${{ secrets.PRIVATE_USERNAME }}
          password: ${{ secrets.PRIVATE_PASSWORD }}
      - name: Build and Publish
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          context: .
          push: true
          build-args: |
            java_type=${{ github.event.inputs.java_type }}
            java_url=${{ github.event.inputs.java_download_url }}
            version=${{ github.event.inputs.java_version }}
            version_suffix=${{ github.event.inputs.java_version_suffix }}
            is_install=${{ github.event.inputs.java_installed }}
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/openjdk:8-${{ steps.set_tag.outputs.latest }}
            ${{ secrets.PRIVATE_REGISTRY }}/openjdk:8-${{ steps.set_tag.outputs.latest }}
            ${{ secrets.DOCKER_REGISTRY }}/openjdk:${{ steps.set_tag.outputs.tag }}
            ${{ secrets.PRIVATE_REGISTRY }}/openjdk:${{ steps.set_tag.outputs.tag }}