name: Build and Publish Docker
on: 
  push:
    tags:
      - '**'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and private service warehouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v3
      - name: Set Docker Tag
        id: set_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TAG=${TAG#*-}
          echo "::set-output name=latest::$TAG"
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Private service warehouse
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY }}
          username: ${{ secrets.PRIVATE_USERNAME }}
          password: ${{ secrets.PRIVATE_PASSWORD }}
      - name: Build and Publish
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/openjdk:8-${{ steps.set_tag.outputs.latest }}
            ${{ secrets.PRIVATE_REGISTRY }}/openjdk:8-${{ steps.set_tag.outputs.latest }}
            ${{ secrets.DOCKER_REGISTRY }}/openjdk:${{ steps.set_tag.outputs.tag }}
            ${{ secrets.PRIVATE_REGISTRY }}/openjdk:${{ steps.set_tag.outputs.tag }}